---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpuexecutioncap: 90
    cpus: 2
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    nictype1: "virtio"

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-16.04

suites:
  - name: default

suites:
  - name: default
    run_list:
      - recipe[conda::install]
      - recipe[conda::repo]
    attributes:
         conda:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
